behaviors:
  Agility:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      beta: 5.0e-3
      buffer_size: 10240
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 3.0e-4
      num_epoch: 3
    network_settings:
      normalize: false
      num_layers: 2
      hidden_units: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
    max_steps: 100000
    time_horizon: 64
    summary_freq: 1000
